services:
  live_leaderboard_backend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - web
      - db_net
    environment:
      - NODE_ENV=production
    

networks:
  web:
    external: true
  db_net:
    external: true
