services:
  live_leaderboard_backend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - web
    environment:
      - NODE_ENV=production
    

networks:
  web:
    external: true